[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "docstring_utils"
authors = [{name = "Jonah Lawrence", email = "jonah@freshidea.com"}]
dynamic = ["version", "description"]